use WFA3DotNet
create table Country(
Cid int not null identity(1,1) primary key,
Cname varchar(30)
)
create table State(
Sid int not null identity(1,1) primary key,
Sname varchar(30),
Cid int foreign key references Country(Cid)
)

create table City(
CityId int not null identity(1,1) primary key,
CityName varchar(30),
Sid int foreign key references State(Sid)
)
select * from State
insert into Country values('India')
insert into Country values('Australia')
insert into Country values('USA')
insert into Country values('South Africa')
select * from Country
insert into State Values('Andhra Pradesh',1)
insert into State Values('Telangana',1)
insert into State Values('Tamilnadu',1)
insert into State Values('Karnataka',1)
insert into State Values('New South Wales',2)
insert into State Values('Victoria',2)
insert into State Values('Queensland',2)
insert into State Values('Tasmania',2)
insert into State Values('California',3)
insert into State Values('Texas',3)
insert into State Values('Florida',3)
insert into State Values('Washington',3)
insert into State Values('Eastern Cape',4)
insert into State Values('Free State',4)
insert into State Values('Northern Cape',4)
insert into State Values('Gauteng',4)
select * from State
insert into City Values('Guntur',1)
insert into City Values('Vijayawada',1)
insert into City Values('Vizag',1)
insert into City Values('Hyderabad',2)
insert into City Values('Warangal',2)
insert into City Values('Nalgonda',2)
insert into City Values('Chennai',3)
insert into City Values('Coimbatore',3)
insert into City Values('Madurai',3)
insert into City Values('Bangalore',4)
insert into City Values('Mangalore',4)
insert into City Values('Hubli',4)
insert into City Values('Sydney',5)
insert into City Values('Newcastle',5)
insert into City Values('Orange',5)
insert into City Values('Melbourne',6)
insert into City Values('Geelong',6)
insert into City Values('Bendigo',6)
insert into City Values('Gold Coast',7)
insert into City Values('Brisbane',7)
insert into City Values('Townsville',7)
insert into City Values('Hobart',8)
insert into City Values('Burnie',8)
insert into City Values('Cygnet',8)
insert into City Values('San Francisco',9)
insert into City Values('Oakland',9)
insert into City Values('Los Angels',9)
insert into City Values('Houston',10)
insert into City Values('Austin',10)
insert into City Values('Dallas',10)
insert into City Values('Miamo',11)
insert into City Values('Orlando',11)
insert into City Values('Tampa',11)
insert into City Values('Seattle',12)
insert into City Values('Olympia',12)
insert into City Values('Tacoma',12)
insert into City Values('Port Elizabeth',13)
insert into City Values('Addo',13)
insert into City Values('Bisho',13)
insert into City Values('Clarens',14)
insert into City Values('Welkom',14)
insert into City Values('Parys',14)
insert into City Values('Kimberly',15)
insert into City Values('Upington',15)
insert into City Values('Kuruman',15)
insert into City Values('Pretoria',16)
insert into City Values('Soweto',16)
insert into City Values('Germiston',16)
select * from City

